import type { GeneratorConfig, UpgradeConfig, MilestoneConfig } from './types';

// ============================================
// GENERADORES — 9 niveles de corrupción
// ============================================
export const GENERATORS: GeneratorConfig[] = [
  {
    id: 'puntero',
    name: 'El Puntero',
    emoji: '🗳️',
    description: 'El operador de barrio que canjea favores por votos.',
    quote: '"¿Te anotás en el plan? Traé a la familia."',
    phase: 'municipal',
    baseCost: 15,
    baseProduction: 0.1,
    costMultiplier: 1.15,
  },
  {
    id: 'canje',
    name: 'El Canje',
    emoji: '🤝',
    description: 'Trueque de favores entre políticos y empresarios locales.',
    quote: '"Hoy por vos, mañana por mí... si hubiera un mañana."',
    phase: 'municipal',
    baseCost: 100,
    baseProduction: 1,
    costMultiplier: 1.15,
  },
  {
    id: 'olla',
    name: 'La Olla Popular',
    emoji: '🍲',
    description: 'La máquina clientelar que moviliza votos con recursos del Estado.',
    quote: '"No es clientelismo, es redistribución solidaria."',
    phase: 'municipal',
    baseCost: 1100,
    baseProduction: 8,
    costMultiplier: 1.15,
  },
  {
    id: 'fundacion',
    name: 'La Fundación Incolora',
    emoji: '🏛️',
    description: 'ONG fachada que lava imagen, consigue subsidios y cobra consultorías.',
    quote: '"Nuestro informe demuestra que tenés que darnos más plata."',
    phase: 'provincial',
    baseCost: 12000,
    baseProduction: 47,
    costMultiplier: 1.15,
  },
  {
    id: 'focusgroup',
    name: 'El Focus Group',
    emoji: '📺',
    description: 'Los opinólogos que construyen narrativa y definen quién es viable.',
    quote: '"No es que sea antipolítico, es que todos son iguales."',
    phase: 'provincial',
    baseCost: 130000,
    baseProduction: 260,
    costMultiplier: 1.15,
  },
  {
    id: 'empresario',
    name: 'El Empresario Amigo',
    emoji: '💼',
    description: 'El que gana todas las licitaciones y pide dolarización cuando conviene.',
    quote: '"¿Competencia desleal? No, ventaja comparativa."',
    phase: 'provincial',
    baseCost: 1400000,
    baseProduction: 1400,
    costMultiplier: 1.15,
  },
  {
    id: 'pauta',
    name: 'La Pauta',
    emoji: '📰',
    description: 'Prensa militante que cubre lo que conviene y silencia lo que no.',
    quote: '"No somos pauteros, somos periodistas comprometidos."',
    phase: 'imperio',
    baseCost: 20000000,
    baseProduction: 7800,
    costMultiplier: 1.15,
  },
  {
    id: 'reeleccion',
    name: 'La re re re elección',
    emoji: '🏖️',
    description: 'Funcionarios que se jubilan con sueldos de lujo y vuelven al rato.',
    quote: '"Dos veces funcionario, tres veces jubilado."',
    phase: 'imperio',
    baseCost: 330000000,
    baseProduction: 44000,
    costMultiplier: 1.15,
  },
  {
    id: 'casta',
    name: 'La Casta Eterna',
    emoji: '👑',
    description: 'Los que nunca se van, sin importar el color ni las elecciones.',
    quote: '"¿Qué pasa si cambiamos la ley para que podamos quedarnos?"',
    phase: 'imperio',
    baseCost: 5100000000,
    baseProduction: 260000,
    costMultiplier: 1.15,
  },
];

// ============================================
// UPGRADES
// ============================================
export const UPGRADES: UpgradeConfig[] = [
  // Click upgrades
  {
    id: 'click_1',
    name: 'El Llamado al Padrino',
    emoji: '📞',
    description: 'Tu primer contacto con alguien que conoce alguien. +1 por clic.',
    cost: 100,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 1 },
    requirement: { type: 'totalInfluencia', value: 100 },
  },
  {
    id: 'click_2',
    name: 'El Grupo de WhatsApp',
    emoji: '📱',
    description: 'Los grupos donde se decide todo sin actas ni reuniones. +2 por clic.',
    cost: 500,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 2 },
    requirement: { type: 'totalInfluencia', value: 1000 },
  },
  {
    id: 'click_3',
    name: 'El Live de Instagram',
    emoji: '🎥',
    description: 'Te hacés el cercano con la gente desde un iPhone 17 Pro Max. +5 por clic.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 5 },
    requirement: { type: 'totalInfluencia', value: 10000 },
  },
  {
    id: 'click_4',
    name: 'La Militancia Digital',
    emoji: '💻',
    description: 'Hordas de trolls y cuentas falsas que defienden tu honor. +20 por clic.',
    cost: 100000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 20 },
    requirement: { type: 'totalInfluencia', value: 100000 },
  },
  {
    id: 'click_5',
    name: 'El DNU Infinito',
    emoji: '📜',
    description: '¿Para qué leyes si podés gobernar con firma y sello? +100 por clic.',
    cost: 10000000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 100 },
    requirement: { type: 'totalInfluencia', value: 10000000 },
  },
  // Generator multipliers
  {
    id: 'gen_puntero_1',
    name: 'La Cuadrilla Completa',
    emoji: '👥',
    description: 'Más punteros, más votos. x2 Punteros.',
    cost: 1000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'puntero', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'puntero', value: 10 },
  },
  {
    id: 'gen_canje_1',
    name: 'Contado con Liqui',
    emoji: '💵',
    description: 'La contabilidad que nadie entiende. x2 Canjes.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'canje', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'canje', value: 10 },
  },
  {
    id: 'gen_olla_1',
    name: 'El Plan Jefazo',
    emoji: '📋',
    description: 'Renovación del plan con otro nombre. x2 Ollas.',
    cost: 55000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'olla', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'olla', value: 10 },
  },
  {
    id: 'gen_fundacion_1',
    name: 'Compra de Encuestadoras',
    emoji: '📊',
    description: 'Los números dicen lo que vos querés. x2 Fundaciones.',
    cost: 600000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'fundacion', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'fundacion', value: 10 },
  },
  {
    id: 'gen_focusgroup_1',
    name: 'El 678 24/7',
    emoji: '🎙️',
    description: 'Más horas de aire, más opinión, menos información. x2 Focus Groups.',
    cost: 6500000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'focusgroup', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'focusgroup', value: 10 },
  },
  {
    id: 'gen_empresario_1',
    name: 'La Licitación con Sobre',
    emoji: '📩',
    description: 'Sobre cerrado, resultado asegurado. x2 Empresarios.',
    cost: 70000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'empresario', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'empresario', value: 10 },
  },
  {
    id: 'gen_pauta_1',
    name: 'Imprenta propia',
    emoji: '🖨️',
    description: 'Lo que sale impreso es la verdad. x2 Medios.',
    cost: 200000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'pauta', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'pauta', value: 10 },
  },
  {
    id: 'gen_reeleccion_1',
    name: 'La Jubilación de Privilegio',
    emoji: '💎',
    description: 'Dos años de trabajo, cuarenta de retiro. x2 Reelecciones.',
    cost: 5000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'reeleccion', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'reeleccion', value: 10 },
  },
  {
    id: 'gen_casta_1',
    name: 'La Reforma Constitucional',
    emoji: '✍️',
    description: 'Si no te gusta la regla, cambiá la regla. x2 Casta.',
    cost: 100000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'casta', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'casta', value: 10 },
  },
  // Passive dinero
  {
    id: 'dinero_1',
    name: 'El Cepo Selectivo',
    emoji: '🏦',
    description: 'Solo los tuyos pueden comprar dólares. +10% dinero pasivo.',
    cost: 2000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.1 },
    requirement: { type: 'totalInfluencia', value: 5000 },
  },
  {
    id: 'dinero_2',
    name: 'La Devaluación Amiga',
    emoji: '📉',
    description: 'Devaluás la moneda y exportás caro. +25% dinero pasivo.',
    cost: 500000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.25 },
    requirement: { type: 'totalInfluencia', value: 500000 },
  },
  {
    id: 'dinero_3',
    name: 'La Fuga Elegante',
    emoji: '✈️',
    description: 'Contado con liqui, fletes, sobreprecios. +50% dinero pasivo.',
    cost: 50000000,
    costResource: 'dinero',
    effect: { type: 'passiveInfluencia', value: 0.5 },
    requirement: { type: 'totalDinero', value: 10000000 },
  },
];

// ============================================
// MILESTONES
// ============================================
export const MILESTONES: MilestoneConfig[] = [
  {
    id: 'm1',
    name: 'Primer Puntero',
    emoji: '🗳️',
    description: 'Tu primer funcionario te debe un favor.',
    requirement: { type: 'totalInfluencia', value: 100 },
    reward: { type: 'clickMultiplier', value: 1 },
  },
  {
    id: 'm2',
    name: 'El Intendente Eterno',
    emoji: '🏛️',
    description: 'Tu candidato gana una elección menor.',
    requirement: { type: 'totalInfluencia', value: 5000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm3',
    name: 'El Que Pasa Facturas',
    emoji: '💳',
    description: 'Descubrís que podés cobrar por ambos lados.',
    requirement: { type: 'totalInfluencia', value: 50000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm4',
    name: 'El Escándalo Controlado',
    emoji: '✈️',
    description: 'Aprendes a manejar crisis mediáticas.',
    requirement: { type: 'totalInfluencia', value: 500000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm5',
    name: 'El Titular de Portada',
    emoji: '⚖️',
    description: 'Tu narrativa define la agenda nacional.',
    requirement: { type: 'totalInfluencia', value: 5000000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm6',
    name: 'La Ley a Medida',
    emoji: '📜',
    description: 'Un senador te pide que redactes la ley.',
    requirement: { type: 'totalInfluencia', value: 50000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm7',
    name: 'El Bipartidismo Eterno',
    emoji: '🔄',
    description: 'Tus ex-empleados controlan 3 ministerios.',
    requirement: { type: 'totalInfluencia', value: 500000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm8',
    name: 'El FMI Cumplidor',
    emoji: '🌍',
    description: 'El FMI te respalda (porque los influiste).',
    requirement: { type: 'totalInfluencia', value: 5000000000 },
    reward: { type: 'productionMultiplier', value: 5 },
  },
  {
    id: 'm9',
    name: 'Atornillado al sillón',
    emoji: '👑',
    description: 'El sistema es tuyo. Los votantes creen que eligieron.',
    requirement: { type: 'totalInfluencia', value: 100000000000 },
    reward: { type: 'productionMultiplier', value: 10 },
  },
];

// ============================================
// PHASE DEFINITIONS
// ============================================
export const PHASE_COLORS = {
  municipal: {
    bg: '#0f1729',
    accent: '#2563eb',
    gold: '#d4af37',
    gradient: 'from-[#0f1729] via-[#1a2744] to-[#0f1729]',
  },
  provincial: {
    bg: '#0f1729',
    accent: '#d4af37',
    gold: '#f59e0b',
    gradient: 'from-[#0f1729] via-[#1a1f2e] to-[#0f1729]',
  },
  imperio: {
    bg: '#0a0a0f',
    accent: '#8b0000',
    gold: '#dc2626',
    gradient: 'from-[#0a0a0f] via-[#1a0a0a] to-[#0a0a0f]',
  },
};

export const PHASE_LABELS = {
  municipal: 'Nivel Municipal',
  provincial: 'Nivel Provincial/Nacional',
  imperio: 'Nivel Imperio',
};

export const PHASE_EMOJIS = {
  municipal: '🏛️',
  provincial: '🏢',
  imperio: '🚀',
};
