import type { GeneratorConfig, UpgradeConfig, MilestoneConfig } from './types';

// ============================================
// GENERADORES — 9 niveles de corrupcion
// ============================================
export const GENERATORS: GeneratorConfig[] = [
  {
    id: 'coctel',
    name: 'El Coctel de Gala',
    emoji: '\uD83C\uDF78',
    description: 'Cenas con concejales en restaurantes caros.',
    quote: '"\u00BFPescado o carne? Ah, y este c\u00F3digo urbano..."',
    phase: 'municipal',
    baseCost: 15,
    baseProduction: 0.1,
    costMultiplier: 1.15,
  },
  {
    id: 'envelope',
    name: 'El Envelope',
    emoji: '\uD83D\uDCB5',
    description: 'Donaciones "no traceables" en efectivo.',
    quote: '"Es un regalo, no un soborno. T\u00E9cnicamente."',
    phase: 'municipal',
    baseCost: 100,
    baseProduction: 1,
    costMultiplier: 1.15,
  },
  {
    id: 'carpeta',
    name: 'La Carpeta de Evidencias',
    emoji: '\uD83D\uDCC1',
    description: 'Informaci\u00F3n comprometedora de funcionarios.',
    quote: '"No es extorsi\u00F3n, es... negociaci\u00F3n asim\u00E9trica."',
    phase: 'municipal',
    baseCost: 1100,
    baseProduction: 8,
    costMultiplier: 1.15,
  },
  {
    id: 'thinktank',
    name: 'El Think Tank Fantasma',
    emoji: '\uD83C\uDFDB\uFE0F',
    description: 'Investigaciones "independientes" a medida.',
    quote: '"Nuestro estudio demuestra que bajar impuestos genera empleo. Sorpresa."',
    phase: 'provincial',
    baseCost: 12000,
    baseProduction: 47,
    costMultiplier: 1.15,
  },
  {
    id: 'pac',
    name: 'El PAC Ilimitado',
    emoji: '\uD83C\uDFE6',
    description: 'Financiaci\u00F3n de campa\u00F1as por toda la cadena.',
    quote: '"No compramos candidatos. Invertimos en leadership."',
    phase: 'provincial',
    baseCost: 130000,
    baseProduction: 260,
    costMultiplier: 1.15,
  },
  {
    id: 'consulting',
    name: 'El Consulting de Cierre',
    emoji: '\uD83C\uDFA4',
    description: 'Spin doctors que inventan narrativas.',
    quote: '"No fue fraude, fue una interpretaci\u00F3n creativa del mandato popular."',
    phase: 'provincial',
    baseCost: 1400000,
    baseProduction: 1400,
    costMultiplier: 1.15,
  },
  {
    id: 'media',
    name: 'El Media Conglomerate',
    emoji: '\uD83D\uDCFA',
    description: 'Cadena de medios propia para agenda-setting.',
    quote: '"No somos propaganda. Somos medios con convicci\u00F3n editorial."',
    phase: 'hegemonic',
    baseCost: 20000000,
    baseProduction: 7800,
    costMultiplier: 1.15,
  },
  {
    id: 'revolving',
    name: 'El Revolving Door',
    emoji: '\uD83D\uDEAA',
    description: 'Ex-funcionarios trabajando para tus empresas.',
    quote: '"No es conflicto de inter\u00E9s. Es reciclaje de talento p\u00FAblico."',
    phase: 'hegemonic',
    baseCost: 330000000,
    baseProduction: 44000,
    costMultiplier: 1.15,
  },
  {
    id: 'constitucional',
    name: 'El Redise\u00F1o Constitucional',
    emoji: '\uD83D\uDCDC',
    description: 'Literalmente reescribir las reglas del juego.',
    quote: '"\u00BFPor qu\u00E9 ganar elecciones si pod\u00E9s cambiar qu\u00E9 significa ganar?"',
    phase: 'hegemonic',
    baseCost: 5100000000,
    baseProduction: 260000,
    costMultiplier: 1.15,
  },
];

// ============================================
// UPGRADES
// ============================================
export const UPGRADES: UpgradeConfig[] = [
  // Click upgrades
  {
    id: 'click_1',
    name: 'Llamaradas Estrategicas',
    emoji: '\uD83D\uDCDE',
    description: 'Tus llamadas son mas persuasivas. +1 influencia por clic.',
    cost: 100,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 1 },
    requirement: { type: 'totalInfluencia', value: 100 },
  },
  {
    id: 'click_2',
    name: 'Blackberry Diplomatico',
    emoji: '\uD83D\uDCF1',
    description: 'Dos dispositivos, doble influencia. +2 por clic.',
    cost: 500,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 2 },
    requirement: { type: 'totalInfluencia', value: 1000 },
  },
  {
    id: 'click_3',
    name: 'Acceso al Salon Privado',
    emoji: '\uD83D\uDD11',
    description: 'Influencia directa cara a cara. +5 por clic.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 5 },
    requirement: { type: 'totalInfluencia', value: 10000 },
  },
  {
    id: 'click_4',
    name: 'La Firma del Operador',
    emoji: '\uD83D\uDCDD',
    description: 'Tu nombre abre puertas. +20 por clic.',
    cost: 100000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 20 },
    requirement: { type: 'totalInfluencia', value: 100000 },
  },
  {
    id: 'click_5',
    name: 'El Warranty Eterno',
    emoji: '\uD83D\uDD39',
    description: 'Tus favores nunca expiran. +100 por clic.',
    cost: 10000000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 100 },
    requirement: { type: 'totalInfluencia', value: 10000000 },
  },
  // Generator multipliers
  {
    id: 'gen_coctel_1',
    name: 'Carta de Vino Premium',
    emoji: '\uD83C\uDF77',
    description: 'Mejor vino, mejores acuerdos. x2 Cocteles.',
    cost: 1000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'coctel', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'coctel', value: 10 },
  },
  {
    id: 'gen_envelope_1',
    name: 'Efectivo en Grande',
    emoji: '\uD83D\uDCB0',
    description: 'Denominaciones mas altas. x2 Envelopes.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'envelope', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'envelope', value: 10 },
  },
  {
    id: 'gen_carpeta_1',
    name: 'Archivo Digital',
    emoji: '\uD83D\uDDA5\uFE0F',
    description: 'Mas evidencia, menos papel. x2 Carpetas.',
    cost: 55000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'carpeta', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'carpeta', value: 10 },
  },
  {
    id: 'gen_thinktank_1',
    name: 'Doctorados Comprados',
    emoji: '\uD83C\uDF93',
    description: 'Credenciales academicas falsas. x2 Think Tanks.',
    cost: 600000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'thinktank', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'thinktank', value: 10 },
  },
  {
    id: 'gen_pac_1',
    name: 'Super PAC H\u00EDbrido',
    emoji: '\uD83C\uDFAF',
    description: 'Fusion de fondos ilimitados. x2 PACs.',
    cost: 6500000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'pac', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'pac', value: 10 },
  },
  {
    id: 'gen_consulting_1',
    name: 'Firma de Relaciones Publicas',
    emoji: '\uD83D\uDC68\u200D\uD83D\uDCBC',
    description: 'Equipo completo de spin. x2 Consulting.',
    cost: 70000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'consulting', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'consulting', value: 10 },
  },
  {
    id: 'gen_media_1',
    name: 'Red de Cable 24/7',
    emoji: '\uD83D\uDCF7',
    description: 'Propaganda las 24 horas. x2 Medios.',
    cost: 200000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'media', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'media', value: 10 },
  },
  {
    id: 'gen_revolving_1',
    name: 'Planta de Reciclaje',
    emoji: '\uD83D\uDED1',
    description: 'Funcionarios ida y vuelta sin parar. x2 Revolving Doors.',
    cost: 5000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'revolving', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'revolving', value: 10 },
  },
  {
    id: 'gen_constitucional_1',
    name: 'Convencion Constituyente',
    emoji: '\uD83D\uDCDB',
    description: 'Una constitucion entera a tu medida. x2 Redise\u00F1os.',
    cost: 100000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'constitucional', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'constitucional', value: 10 },
  },
  // Passive dinero
  {
    id: 'dinero_1',
    name: 'Cuenta Suiza Basica',
    emoji: '\uD83C\uDDE8\uD83C\uDDED',
    description: 'Empezas a convertir influencia en dinero. +10% dinero pasivo.',
    cost: 2000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.1 },
    requirement: { type: 'totalInfluencia', value: 5000 },
  },
  {
    id: 'dinero_2',
    name: 'Fondo de Inversiones',
    emoji: '\uD83D\uDCC8',
    description: 'Tu dinero genera mas dinero. +25% dinero pasivo.',
    cost: 500000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.25 },
    requirement: { type: 'totalInfluencia', value: 500000 },
  },
  {
    id: 'dinero_3',
    name: 'Holding Offshore',
    emoji: '\uD83C\uDFDD\uFE0F',
    description: 'Estructura multinacional. +50% dinero pasivo.',
    cost: 50000000,
    costResource: 'dinero',
    effect: { type: 'passiveInfluencia', value: 0.5 },
    requirement: { type: 'totalDinero', value: 10000000 },
  },
];

// ============================================
// MILESTONES
// ============================================
export const MILESTONES: MilestoneConfig[] = [
  {
    id: 'm1',
    name: 'Amigo del Concejal',
    emoji: '\uD83E\uDD1D',
    description: 'Tu primer funcionario te debe un favor.',
    requirement: { type: 'totalInfluencia', value: 100 },
    reward: { type: 'clickMultiplier', value: 1 },
  },
  {
    id: 'm2',
    name: 'El Relevo',
    emoji: '\uD83D\uDD04',
    description: 'Tu candidato gana una eleccion menor.',
    requirement: { type: 'totalInfluencia', value: 5000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm3',
    name: 'La Cuenta Doble',
    emoji: '\uD83D\uDCB3',
    description: 'Descubris que podes cobrar por ambos lados.',
    requirement: { type: 'totalInfluencia', value: 50000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm4',
    name: 'El Escandalo Controlado',
    emoji: '\uD83D\uDCAC',
    description: 'Aprendes a manejar crisis mediaticas.',
    requirement: { type: 'totalInfluencia', value: 500000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm5',
    name: 'El Titular de Portada',
    emoji: '\uD83D\uDCF0',
    description: 'Tu narrativa define la agenda nacional.',
    requirement: { type: 'totalInfluencia', value: 5000000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm6',
    name: 'La Ley a Medida',
    emoji: '\uD83D\uDCDC',
    description: 'Un senador te pide que redactes la ley.',
    requirement: { type: 'totalInfluencia', value: 50000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm7',
    name: 'El Estado Dentro del Estado',
    emoji: '\uD83C\uDFDB\uFE0F',
    description: 'Tus ex-empleados controlan 3 ministerios.',
    requirement: { type: 'totalInfluencia', value: 500000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm8',
    name: 'El Respaldo Internacional',
    emoji: '\uD83C\uDF0D',
    description: 'El FMI te respalda (porque los influiste).',
    requirement: { type: 'totalInfluencia', value: 5000000000 },
    reward: { type: 'productionMultiplier', value: 5 },
  },
  {
    id: 'm9',
    name: 'Democracia, Inc.',
    emoji: '\uD83D\uDC51',
    description: 'El sistema es tuyo. Los votantes creen que eligieron.',
    requirement: { type: 'totalInfluencia', value: 100000000000 },
    reward: { type: 'productionMultiplier', value: 10 },
  },
];

// ============================================
// PHASE DEFINITIONS
// ============================================
export const PHASE_COLORS = {
  municipal: {
    bg: '#0f1729',
    accent: '#2563eb',
    gold: '#d4af37',
    gradient: 'from-[#0f1729] via-[#1a2744] to-[#0f1729]',
  },
  provincial: {
    bg: '#0f1729',
    accent: '#d4af37',
    gold: '#f59e0b',
    gradient: 'from-[#0f1729] via-[#1a1f2e] to-[#0f1729]',
  },
  hegemonic: {
    bg: '#0a0a0f',
    accent: '#8b0000',
    gold: '#dc2626',
    gradient: 'from-[#0a0a0f] via-[#1a0a0a] to-[#0a0a0f]',
  },
};

export const PHASE_LABELS = {
  municipal: 'Nivel Municipal',
  provincial: 'Nivel Provincial/Nacional',
  hegemonic: 'Nivel Hegemonico',
};

export const PHASE_EMOJIS = {
  municipal: '\uD83C\uDFDB\uFE0F',
  provincial: '\uD83C\uDFE2',
  hegemonic: '\uD83D\uDE80',
};
