// ============================================
// DEMOCRACIA S.A. — Game Configuration Data
// ============================================

const GENERATORS = [
  {
    id: 'puntero',
    name: 'El Puntero',
    emoji: '\u{1F5F3}\uFE0F',
    description: 'El operador de barrio que canjea favores por votos.',
    quote: '"\u00BFTe anot\u00E1s en el plan? Tra\u00E9 a la familia."',
    phase: 'municipal',
    baseCost: 15,
    baseProduction: 0.1,
    costMultiplier: 1.15,
  },
  {
    id: 'canje',
    name: 'El Canje',
    emoji: '\u{1F91D}',
    description: 'Trueque de favores entre pol\u00EDticos y empresarios locales.',
    quote: '"Hoy por vos, ma\u00F1ana por m\u00ED... si hubiera un ma\u00F1ana."',
    phase: 'municipal',
    baseCost: 100,
    baseProduction: 1,
    costMultiplier: 1.15,
  },
  {
    id: 'olla',
    name: 'La Olla Popular',
    emoji: '\u{1F372}',
    description: 'La m\u00E1quina clientelar que moviliza votos con recursos del Estado.',
    quote: '"No es clientelismo, es redistribuci\u00F3n solidaria."',
    phase: 'municipal',
    baseCost: 1100,
    baseProduction: 8,
    costMultiplier: 1.15,
  },
  {
    id: 'fundacion',
    name: 'La Fundaci\u00F3n Incolora',
    emoji: '\u{1F3DB}\uFE0F',
    description: 'ONG fachada que lava imagen, consigue subsidios y cobra consultor\u00EDas.',
    quote: '"Nuestro informe demuestra que ten\u00E9s que darnos m\u00E1s plata."',
    phase: 'provincial',
    baseCost: 12000,
    baseProduction: 47,
    costMultiplier: 1.15,
  },
  {
    id: 'focusgroup',
    name: 'El Focus Group',
    emoji: '\u{1F4FA}',
    description: 'Los opin\u00F3logos que construyen narrativa y definen qui\u00E9n es viable.',
    quote: '"No es que sea antipol\u00EDtico, es que todos son iguales."',
    phase: 'provincial',
    baseCost: 130000,
    baseProduction: 260,
    costMultiplier: 1.15,
  },
  {
    id: 'empresario',
    name: 'El Empresario Amigo',
    emoji: '\u{1F4BC}',
    description: 'El que gana todas las licitaciones y pide dolarizaci\u00F3n cuando conviene.',
    quote: '"\u00BFCompetencia desleal? No, ventaja comparativa."',
    phase: 'provincial',
    baseCost: 1400000,
    baseProduction: 1400,
    costMultiplier: 1.15,
  },
  {
    id: 'pauta',
    name: 'La Pauta',
    emoji: '\u{1F4F0}',
    description: 'Prensa militante que cubre lo que conviene y silencia lo que no.',
    quote: '"No somos pauteros, somos periodistas comprometidos."',
    phase: 'imperio',
    baseCost: 20000000,
    baseProduction: 7800,
    costMultiplier: 1.15,
  },
  {
    id: 'reeleccion',
    name: 'La re re re elecci\u00F3n',
    emoji: '\u{1F3D6}\uFE0F',
    description: 'Funcionarios que se jubilan con sueldos de lujo y vuelven al rato.',
    quote: '"Dos veces funcionario, tres veces jubilado."',
    phase: 'imperio',
    baseCost: 330000000,
    baseProduction: 44000,
    costMultiplier: 1.15,
  },
  {
    id: 'casta',
    name: 'La Casta Eterna',
    emoji: '\u{1F451}',
    description: 'Los que nunca se van, sin importar el color ni las elecciones.',
    quote: '"\u00BFQu\u00E9 pasa si cambiamos la ley para que podamos quedarnos?"',
    phase: 'imperio',
    baseCost: 5100000000,
    baseProduction: 260000,
    costMultiplier: 1.15,
  },
];

const UPGRADES = [
  // Click upgrades
  {
    id: 'click_1',
    name: 'El Llamado al Padrino',
    emoji: '\u{1F4DE}',
    description: 'Tu primer contacto con alguien que conoce alguien. +1 por clic.',
    cost: 100,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 1 },
    requirement: { type: 'totalInfluencia', value: 100 },
  },
  {
    id: 'click_2',
    name: 'El Grupo de WhatsApp',
    emoji: '\u{1F4F1}',
    description: 'Los grupos donde se decide todo sin actas ni reuniones. +2 por clic.',
    cost: 500,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 2 },
    requirement: { type: 'totalInfluencia', value: 1000 },
  },
  {
    id: 'click_3',
    name: 'El Live de Instagram',
    emoji: '\u{1F3A5}',
    description: 'Te hac\u00E9s el cercano con la gente desde un iPhone 17 Pro Max. +5 por clic.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'clickMultiplier', value: 5 },
    requirement: { type: 'totalInfluencia', value: 10000 },
  },
  {
    id: 'click_4',
    name: 'La Militancia Digital',
    emoji: '\u{1F4BB}',
    description: 'Hordas de trolls y cuentas falsas que defienden tu honor. +20 por clic.',
    cost: 100000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 20 },
    requirement: { type: 'totalInfluencia', value: 100000 },
  },
  {
    id: 'click_5',
    name: 'El DNU Infinito',
    emoji: '\u{1F4DC}',
    description: '\u00BFPara qu\u00E9 leyes si pod\u00E9s gobernar con firma y sello? +100 por clic.',
    cost: 10000000,
    costResource: 'dinero',
    effect: { type: 'clickMultiplier', value: 100 },
    requirement: { type: 'totalInfluencia', value: 10000000 },
  },
  // Generator multipliers
  {
    id: 'gen_puntero_1',
    name: 'La Cuadrilla Completa',
    emoji: '\u{1F465}',
    description: 'M\u00E1s punteros, m\u00E1s votos. x2 Punteros.',
    cost: 1000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'puntero', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'puntero', value: 10 },
  },
  {
    id: 'gen_canje_1',
    name: 'Contado con Liqui',
    emoji: '\u{1F4B5}',
    description: 'La contabilidad que nadie entiende. x2 Canjes.',
    cost: 5000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'canje', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'canje', value: 10 },
  },
  {
    id: 'gen_olla_1',
    name: 'El Plan Jefazo',
    emoji: '\u{1F4CB}',
    description: 'Renovaci\u00F3n del plan con otro nombre. x2 Ollas.',
    cost: 55000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'olla', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'olla', value: 10 },
  },
  {
    id: 'gen_fundacion_1',
    name: 'Compra de Encuestadoras',
    emoji: '\u{1F4CA}',
    description: 'Los n\u00FAmeros dicen lo que vos quer\u00E9s. x2 Fundaciones.',
    cost: 600000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'fundacion', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'fundacion', value: 10 },
  },
  {
    id: 'gen_focusgroup_1',
    name: 'El 678 24/7',
    emoji: '\u{1F399}\uFE0F',
    description: 'M\u00E1s horas de aire, m\u00E1s opini\u00F3n, menos informaci\u00F3n. x2 Focus Groups.',
    cost: 6500000,
    costResource: 'influencia',
    effect: { type: 'generatorMultiplier', targetId: 'focusgroup', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'focusgroup', value: 10 },
  },
  {
    id: 'gen_empresario_1',
    name: 'La Licitaci\u00F3n con Sobre',
    emoji: '\u{1F4E9}',
    description: 'Sobre cerrado, resultado asegurado. x2 Empresarios.',
    cost: 70000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'empresario', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'empresario', value: 10 },
  },
  {
    id: 'gen_pauta_1',
    name: 'Imprenta propia',
    emoji: '\u{1F5A8}\uFE0F',
    description: 'Lo que sale impreso es la verdad. x2 Medios.',
    cost: 200000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'pauta', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'pauta', value: 10 },
  },
  {
    id: 'gen_reeleccion_1',
    name: 'La Jubilaci\u00F3n de Privilegio',
    emoji: '\u{1F48E}',
    description: 'Dos a\u00F1os de trabajo, cuarenta de retiro. x2 Reelecciones.',
    cost: 5000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'reeleccion', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'reeleccion', value: 10 },
  },
  {
    id: 'gen_casta_1',
    name: 'La Reforma Constitucional',
    emoji: '\u270D\uFE0F',
    description: 'Si no te gusta la regla, cambi\u00E1 la regla. x2 Casta.',
    cost: 100000000000,
    costResource: 'dinero',
    effect: { type: 'generatorMultiplier', targetId: 'casta', value: 2 },
    requirement: { type: 'generatorCount', targetId: 'casta', value: 10 },
  },
  // Passive dinero
  {
    id: 'dinero_1',
    name: 'El Cepo Selectivo',
    emoji: '\u{1F3E6}',
    description: 'Solo los tuyos pueden comprar d\u00F3lares. +10% dinero pasivo.',
    cost: 2000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.1 },
    requirement: { type: 'totalInfluencia', value: 5000 },
  },
  {
    id: 'dinero_2',
    name: 'La Devaluaci\u00F3n Amiga',
    emoji: '\u{1F4C9}',
    description: 'Devalu\u00E1s la moneda y export\u00E1s caro. +25% dinero pasivo.',
    cost: 500000,
    costResource: 'influencia',
    effect: { type: 'passiveInfluencia', value: 0.25 },
    requirement: { type: 'totalInfluencia', value: 500000 },
  },
  {
    id: 'dinero_3',
    name: 'La Fuga Elegante',
    emoji: '\u2708\uFE0F',
    description: 'Contado con liqui, fletes, sobreprecios. +50% dinero pasivo.',
    cost: 50000000,
    costResource: 'dinero',
    effect: { type: 'passiveInfluencia', value: 0.5 },
    requirement: { type: 'totalDinero', value: 10000000 },
  },
];

const MILESTONES = [
  {
    id: 'm1',
    name: 'Primer Puntero',
    emoji: '\u{1F5F3}\uFE0F',
    description: 'Tu primer funcionario te debe un favor.',
    requirement: { type: 'totalInfluencia', value: 100 },
    reward: { type: 'clickMultiplier', value: 1 },
  },
  {
    id: 'm2',
    name: 'El Intendente Eterno',
    emoji: '\u{1F3DB}\uFE0F',
    description: 'Tu candidato gana una elecci\u00F3n menor.',
    requirement: { type: 'totalInfluencia', value: 5000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm3',
    name: 'El Que Pasa Facturas',
    emoji: '\u{1F4B3}',
    description: 'Descubr\u00EDs que pod\u00E9s cobrar por ambos lados.',
    requirement: { type: 'totalInfluencia', value: 50000 },
    reward: { type: 'productionMultiplier', value: 1.5 },
  },
  {
    id: 'm4',
    name: 'El Esc\u00E1ndalo Controlado',
    emoji: '\u2708\uFE0F',
    description: 'Aprendes a manejar crisis medi\u00E1ticas.',
    requirement: { type: 'totalInfluencia', value: 500000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm5',
    name: 'El Titular de Portada',
    emoji: '\u2696\uFE0F',
    description: 'Tu narrativa define la agenda nacional.',
    requirement: { type: 'totalInfluencia', value: 5000000 },
    reward: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'm6',
    name: 'La Ley a Medida',
    emoji: '\u{1F4DC}',
    description: 'Un senador te pide que redactes la ley.',
    requirement: { type: 'totalInfluencia', value: 50000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm7',
    name: 'El Bipartidismo Eterno',
    emoji: '\u{1F504}',
    description: 'Tus ex-empleados controlan 3 ministerios.',
    requirement: { type: 'totalInfluencia', value: 500000000 },
    reward: { type: 'productionMultiplier', value: 3 },
  },
  {
    id: 'm8',
    name: 'El FMI Cumplidor',
    emoji: '\u{1F30D}',
    description: 'El FMI te respalda (porque los influiste).',
    requirement: { type: 'totalInfluencia', value: 5000000000 },
    reward: { type: 'productionMultiplier', value: 5 },
  },
  {
    id: 'm9',
    name: 'Atornillado al sill\u00F3n',
    emoji: '\u{1F451}',
    description: 'El sistema es tuyo. Los votantes creen que eligieron.',
    requirement: { type: 'totalInfluencia', value: 100000000000 },
    reward: { type: 'productionMultiplier', value: 10 },
  },
];

const PHASE_LABELS = {
  municipal: 'Nivel Municipal',
  provincial: 'Nivel Provincial/Nacional',
  imperio: 'Nivel Imperio',
};

const PHASE_EMOJIS = {
  municipal: '\u{1F3DB}\uFE0F',
  provincial: '\u{1F3E2}',
  imperio: '\u{1F680}',
};

const HEADLINES = [
  // === MUNICIPAL ===
  { text: '"Concejal sorprendido contando sobres en el ba\u00F1o del restaurante. Dice que clasificaba correspondencia."', phase: 'municipal' },
  { text: '"El intendente firma ordenanza que beneficia a amigos personales. Nombra 47 amigos."', phase: 'municipal' },
  { text: '"Think Tank municipal revela que el 100% de los encuestados apoya al concejal que los encuest\u00F3."', phase: 'municipal' },
  { text: '"Funcionario invierte todo su sueldo en cocteles de gala. Su abogado dice que es gasto representativo."', phase: 'municipal' },
  { text: '"La oposici\u00F3n denuncia irregularidades. Nadie los escucha porque estaban en un coctel de gala."', phase: 'municipal' },
  { text: '"Periodista descubre que el presupuesto municipal se gasta en asesoramientos. Son 12 sobrinos."', phase: 'municipal' },
  { text: '"Empresa fantasma dona a campa\u00F1a electoral. Su director es el portero del concejo."', phase: 'municipal' },
  { text: '"Auditor\u00EDa revela que el 80% del presupuesto se fue en vi\u00E1ticos de investigaci\u00F3n. A Canc\u00FAn."', phase: 'municipal' },
  { text: '"El defensor del pueblo result\u00F3 ser sobrino del alcalde. Coincidencias del destino."', phase: 'municipal' },
  { text: '"Transparencia: el municipio publica sus gastos. Todos los n\u00FAmeros est\u00E1n tachados."', phase: 'municipal' },
  { text: '"El cepo al d\u00F3lar fue un \u00E9xito: los que ya ten\u00EDan d\u00F3lares no tuvieron problemas."', phase: 'municipal' },
  { text: '"Pol\u00E9mica por los viajes al exterior: el funcionario asegur\u00F3 que era por trabajo y los esqu\u00EDes eran incidentales."', phase: 'municipal' },
  { text: '"El Congreso debate si declarar feriado nacional el d\u00EDa despu\u00E9s de cada feriado"', phase: 'municipal' },
  { text: '"Panaderos advierten: el pan ahora se vender\u00E1 por suscripci\u00F3n mensual"', phase: 'municipal' },
  { text: '"Revelan que el colectivo llega tarde para fomentar la paciencia social"', phase: 'municipal' },
  { text: '"Gobierno lanza programa \'Precios Cuidados Emocionales\' para evitar crisis existenciales en el s\u00FAper"', phase: 'municipal' },
  { text: '"Sindicato convoca paro contra medida que todav\u00EDa no fue anunciada"', phase: 'municipal' },
  { text: '"El funcionario renunci\u00F3 por motivos personales. Ma\u00F1ana asume en otro cargo."', phase: 'municipal' },

  // === PROVINCIAL ===
  { text: '"Senador pide investigar interferencia extranjera en las elecciones. Su financista es suizo."', phase: 'provincial' },
  { text: '"Think Tank revela que bajar impuestos a los ricos genera empleo. Sorpresa: el estudio lo pag\u00F3 un rico."', phase: 'provincial' },
  { text: '"El gobernador anuncia plan de transparencia. No incluye su propio financiamiento."', phase: 'provincial' },
  { text: '"Consultora pol\u00EDtica cobra $5M por manejo de crisis. La crisis es que los pagan demasiado."', phase: 'provincial' },
  { text: '"Medio de comunicaci\u00F3n cambia su l\u00EDnea editorial. El nuevo due\u00F1o es un amigo de la democracia."', phase: 'provincial' },
  { text: '"Funcionario renuncia para trabajar en el sector privado. Al d\u00EDa siguiente ingresa a empresa que regulaba."', phase: 'provincial' },
  { text: '"La Corte falla 5-4 a favor del financiador del juez que escribi\u00F3 la opini\u00F3n de la mayor\u00EDa."', phase: 'provincial' },
  { text: '"Diputado aprueba ley de \u00E9tica p\u00FAblica. \u00C9l es el primero en violarla."', phase: 'provincial' },
  { text: '"Encuesta: el 73% de los ciudadanos conf\u00EDa en las instituciones. La encuesta se pag\u00F3 con dinero p\u00FAblico."', phase: 'provincial' },
  { text: '"Lobby cobra $200/hora por reuniones con legisladores. La reuni\u00F3n dura 5 minutos."', phase: 'provincial' },
  { text: '"Nueva auditor\u00EDa revela que nadie sabe d\u00F3nde est\u00E1 el dinero, pero todos est\u00E1n de acuerdo en que se gast\u00F3 bien."', phase: 'provincial' },
  { text: '"D\u00F3lar blue another day: la brecha ya es m\u00E1s ancha que la 9 de Julio."', phase: 'provincial' },
  { text: '"La casta se renueva: cambian las caras, el sueldo y el auto, pero no el sistema."', phase: 'provincial' },
  { text: '"Se aprob\u00F3 la ley de medios: ahora los amigos tienen m\u00E1s canales."', phase: 'provincial' },
  { text: '"Opinolog\u00EDa: dos economistas, tres opiniones, cero soluciones."', phase: 'provincial' },
  { text: '"El debate presidencial dur\u00F3 dos horas. Los argentinos siguen esperando desde 1983."', phase: 'provincial' },
  { text: '"Inflaci\u00F3n mensual: el gobierno prefiere hablar de inflaci\u00F3n interanual, suena m\u00E1s estable."', phase: 'provincial' },
  { text: '"Nuevo aumento de tarifas: la promesa era que iba a bajar, pero qued\u00F3 en que sube menos que antes."', phase: 'provincial' },
  { text: '"La oposici\u00F3n present\u00F3 un proyecto. El oficialismo lo aplaudi\u00F3. Nadie lo ley\u00F3."', phase: 'provincial' },
  { text: '"Encuesta: el 87% de los argentinos est\u00E1 cansado de las encuestas."', phase: 'provincial' },
  { text: '"El clima econ\u00F3mico ser\u00E1 inestable con probabilidad de aumentos aislados"', phase: 'provincial' },
  { text: '"Expertos se\u00F1alan que la oposici\u00F3n ya tiene plan B, C y D, falta el A"', phase: 'provincial' },
  { text: '"Expertos recomiendan respirar hondo antes de mirar el resumen de la tarjeta"', phase: 'provincial' },
  { text: '"Lanzan curso intensivo para entender promociones del supermercado"', phase: 'provincial' },
  { text: '"Documento opositor propone \'cambiar el rumbo\' sin especificar hacia d\u00F3nde"', phase: 'provincial' },
  { text: '"Diputado propone indexar la realidad a la inflaci\u00F3n para \'evitar distorsiones\'"', phase: 'provincial' },
  { text: '"Analistas confirman que el plan econ\u00F3mico consiste en \'ver qu\u00E9 pasa\'"', phase: 'provincial' },
  { text: '"Senado aprueba ley para que las discusiones pol\u00EDticas incluyan al menos un dato real"', phase: 'provincial' },
  { text: '"Nuevo programa: \'Precios Sorprendidos\', donde nadie sabe cu\u00E1nto va a pagar"', phase: 'provincial' },
  { text: '"Referente asegura que el pa\u00EDs necesita di\u00E1logo, pero no \'con esos\'"', phase: 'provincial' },
  { text: '"Nuevo \u00EDndice mide cu\u00E1nto dura la alegr\u00EDa despu\u00E9s de cobrar"', phase: 'provincial' },
  { text: '"Encuesta revela que la mitad del pa\u00EDs cree que la otra mitad entiende lo que est\u00E1 pasando"', phase: 'provincial' },
  { text: '"Economista heterodoxo explica que emitir no genera inflaci\u00F3n \'si se hace con cari\u00F1o\'"', phase: 'provincial' },
  { text: '"Dirigente aclara que no es interna, es \'debate enriquecedor con gritos\'"', phase: 'provincial' },
  { text: '"Espacio progresista lanza app para indignarse de forma m\u00E1s eficiente"', phase: 'provincial' },

  // === IMPERIO ===
  { text: '"El presidente anuncia reforma constitucional. No recuerda qui\u00E9n se la sugiri\u00F3."', phase: 'imperio' },
  { text: '"La oposici\u00F3n acepta di\u00E1logo. En el restaurante de tu propiedad."', phase: 'imperio' },
  { text: '"Inflaci\u00F3n baja. Tus economistas dicen que era obvio. Los dem\u00E1s economistas no existen."', phase: 'imperio' },
  { text: '"La OEA env\u00EDa observadores electorales. Los observadores son tus ex-empleados."', phase: 'imperio' },
  { text: '"WikiLeaks revela que Democracia S.A. es cliente frecuente. Fuentes dicen que es un placer hacer negocios."', phase: 'imperio' },
  { text: '"El FMI aprueba un pr\u00E9stamo de $50B. El director del FMI cen\u00F3 en tu casa la noche anterior."', phase: 'imperio' },
  { text: '"El Congreso aprueba la Ley de Honestidad Pol\u00EDtica. Todos votan a favor sin leerla. Como siempre."', phase: 'imperio' },
  { text: '"El expresidente admite que nunca tom\u00F3 una decisi\u00F3n sola. Menciona un amigo influyente. Su abogado dice que era su gato."', phase: 'imperio' },
  { text: '"Los tres poderes del Estado confirman que trabajan en armon\u00EDa. Coinciden en que vos dec\u00EDs qu\u00E9 hacer."', phase: 'imperio' },
  { text: '"La calidad democr\u00E1tica es del 0%. El gobierno la califica de \u00E9xito rotundo."', phase: 'imperio' },
  { text: '"Devaluaci\u00F3n express: los que se adelantaron ganan, los que no... votan de nuevo."', phase: 'imperio' },
  { text: '"El FMI pide m\u00E1s ajuste. La respuesta del gobierno: otro viaje a Nueva York."', phase: 'imperio' },
  { text: '"Funcionario explica que la incertidumbre \'es parte del atractivo del pa\u00EDs\'"', phase: 'imperio' },
  { text: '"Se establece que toda cadena nacional deber\u00E1 incluir un plot twist"', phase: 'imperio' },
  { text: '"La oposici\u00F3n denuncia con firmeza lo mismo que defend\u00EDa hace seis meses"', phase: 'imperio' },
  { text: '"Dirigente opositor afirma que ahora s\u00ED tienen un rumbo claro de cara a las pr\u00F3ximas elecciones, pero no lo quieren spoilear"', phase: 'imperio' },
  { text: '"Bloque opositor critica falta de consenso y propone m\u00E1s desacuerdos"', phase: 'imperio' },
  { text: '"Gobierno anuncia medida hist\u00F3rica; oposici\u00F3n la rechaza; ciudadanos googlean \'qu\u00E9 significa\'"', phase: 'imperio' },
  { text: '"Oficialismo asegura que todo mejora; oposici\u00F3n que todo empeora; pa\u00EDs entra en estado cu\u00E1ntico"', phase: 'imperio' },
  { text: '"Gobierno lanza plan; oposici\u00F3n lanza cr\u00EDtica; ciudadanos lanzan suspiros"', phase: 'imperio' },
  { text: '"Oficialismo y oposici\u00F3n coinciden en que el problema es el otro"', phase: 'imperio' },
  { text: '"Se anuncia acuerdo pol\u00EDtico que ser\u00E1 desacordado en las pr\u00F3ximas horas"', phase: 'imperio' },
  { text: '"Encuesta revela que el pa\u00EDs est\u00E1 mejor, peor y m\u00E1s o menos igual al mismo tiempo"', phase: 'imperio' },
  { text: '"Expertos recomiendan no discutir de pol\u00EDtica en cenas para preservar v\u00EDnculos humanos"', phase: 'imperio' },
  { text: '"Columna: \'No entiendo nada, pero tengo una postura firme\'"', phase: 'imperio' },
];

function getRandomHeadline(phase, exclude) {
  const pool = HEADLINES.filter(h => h.phase === phase);
  const available = exclude ? pool.filter(h => h.text !== exclude) : pool;
  if (available.length === 0) return pool[0] ? pool[0].text : 'Sin noticias nuevas... por ahora.';
  return available[Math.floor(Math.random() * available.length)].text;
}
